### PR TITLE
[fix] Missing procmail dependency

### PR DESCRIPTION
**Pull request by JocelynDelalande**
The main.cf references procmail, but there is no dpkg dependency to it.

Actually, I managed to get my ynh installation to an incoherent state, uninstalling procmail, nothing prevented me from doing this.

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
(please tell me if that was not relevant to PR to stable)

**Comment by JocelynDelalande** [comment]
@julienmalik bump ?

**Comment by jeromelebleu** [comment]
Done wite https://github.com/YunoHost/yunohost/commit/c8b481344014ba398046b1055f120184a8de5200. Thanks!

**Comment by JocelynDelalande** [comment]
@jeromelebleu thanks :) maybe you should put in  bold statement in this github repository summary that it's deprecated.

**Pull request closed without merging**
